# Generated by Django 6.0.7 on 2026-08-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('Shipping Line / Liner Operator', 'Shipping Line / Liner Operator'), ('NVOCC', 'NVOCC'), ('Freight Forwarder', 'Freight Forwarder'), ('Shipping Agency', 'Shipping Agency'), ('Port / Terminal Operator', 'Port / Terminal Operator'), ('Container Depot', 'Container Depot'), ('Logistics Provider / 3PL / 4PL', 'Logistics Provider / 3PL / 4PL'), ('Customs Broker', 'Customs Broker'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
