# Generated by Django 6.0.7 on 2026-08-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='crm_synced',
            field=models.BooleanField(default=False),
        ),
    ]
