# Generated by Django 6.0.7 on 2026-08-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_crm_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='crm_synced',
        ),
    ]
